sausage-landing/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sausage-landing/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sausage-landing/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

sausage-landing/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @copyCat = "우리 엄마가 먹는거로\n장난치는거 아니랬어..\n- 소세지 어록 -"
    @appstore = "https://www.facebook.com/"
    @intro = "BHC치킨의 비양심적인 가격인상,
              총각네 야채가게 대표의 말도 안되는 갑질.
              최근의 뉴스들이지만, 한편으론 언제 들려와도
              이상하지 않을 익숙한 소식들입니다.

              이런 악순환을 끝내서
              내 자식이 안전한 먹거리를 먹을 수 있도록,
              소비자들이 양심기업들의 제품만을 구매해
              시장의 선순환을 가져올 수 있도록.

              소세지에서 당신의 건강한 먹거리 소비를
              시작해보세요."
    @service = [
        "내가 관심있는 먹거리에 대한
        뉴스, 정부의 대처 등
        최신 소식들을 받아보고
        항상 안전하고 합리적인
        먹거리 소비를 시작해보세요",

        "여러 소비자들이 직접 들려주는
        먹거리들에 대한 다양한 이야기와
        내가 겪었던 일 등을 업로드하며
        평소에 몰랐던 것, 또는
        나만 알고있던 것을
        많은 사람들과 공유해보세요",

        "먹거리를 만드는 기업들이
        얼마나 소비자를 생각하는지
        좋아요, 뉴스 등 여러 지표로
        분석한 정보를 통해
        좋은 기업인지 나쁜 기업인지
        직접 확인해보세요"
    ]
    @download = "현재 소세지는 안드로이드에서 서비스중이며,
                아이폰과 웹에서도 서비스를 제공하기 위해 노력중입니다
                당신의 핸드폰에서 먼저 소세지를 시작해보세요!"
  end
end

sausage-landing/app/helpers/application_helper.rb
module ApplicationHelper
end

sausage-landing/app/helpers/home_helper.rb
module HomeHelper
end

sausage-landing/app/views/home/index.html.erb
<div id="home-index">
  <nav class="_navbar _vcenter-positioner">
    <div class="_flex-grow-1">
      <%= link_to home_index_path do %>
          <%= image_tag "logo_sausage", class: "logo-img" %>
      <% end %>
    </div>

    <%= link_to "소개", home_index_path(anchor: "intro"), class: "nav-text _fs-4 _white" %>
    <%= link_to "서비스", home_index_path(anchor: "service"), class: "nav-text _fs-4 _white" %>
    <%= link_to "다운로드", home_index_path(anchor: "download"), class: "nav-text _fs-4 _white" %>
  </nav>

  <div class="header-container _vcenter-positioner">
    <div class="_full-positioner">
      <%= image_tag "background_sausage.jpg", class: "background-img" %>
    </div>
    <div class="_filter _full-positioner"></div>

    <div class="header-box _column-positioner _vcenter-positioner
      _hcenter-positioner">
      <div class="_text-center _z-index-front">
        <%= simple_format @copyCat, class: "_fs-title _white _f-line-narrow" %>
      </div>

      <div class="header-icon-box _vbottom-positioner">
        <%= link_to @appstore, class: "icon-margin" do %>
            <%= image_tag "icon_google_play", class: "_store-icon" %>
        <% end %>
        <%= link_to "", class: "filter-container icon-margin" do %>
            <%= image_tag "icon_appstore", class: "_store-icon" %>
            <div class="button-filter _full-positioner _vcenter-positioner _hcenter-positioner">
              <p class="_fs-4 _white">준비중입니다</p>
            </div>
        <% end %>
      </div>
    </div>
    <!--소세지가 뭔가요?-->
  </div>

  <div class="intro-container _hcenter-positioner" id="intro">
    <div class="content-box _vcenter-positioner">
      <%= image_tag "image_phone.png", class: "phone-img" %>
      <div class="intro-text">
        <p class="_fs-2 _black">왜 우리는 항상 먹거리때문에<br>불안에 떨어야하나요?</p>
        <%= simple_format @intro, class: "_fs-4 _dark-gray" %>
      </div>
    </div>
  </div>

  <div class="service-container _hcenter-positioner" id="service">
    <div class="content-box">
      <div class="_vcenter-positioner _hcenter-positioner _no-p-margin">
        <p class="_fs-3 _white">당신이</p>
        <%= image_tag "logo_sausage", class: "logo-img" %>
        <p class="_fs-3 _white">에서 할 수 있는 일</p>
      </div>
      <div class="service-circle-group _hcenter-positioner">
        <div class="service-circle _text-center">
          <%= image_tag "circle_news", class: "circle-img" %>
          <p class="_fs-4 _white">최신 이슈 받아보기</p>
          <%= simple_format @service[0], class: "_fs-5 _light-gray" %>
        </div>
        <div class="service-circle _text-center">
          <%= image_tag "circle_community", class: "circle-img" %>
          <p class="_fs-4 _white">사람들과 정보 공유하기</p>
          <%= simple_format @service[1], class: "_fs-5 _light-gray" %>
        </div>
        <div class="service-circle _text-center">
          <%= image_tag "circle_company", class: "circle-img" %>
          <p class="_fs-4 _white">기업점수 보기</p>
          <%= simple_format @service[2], class: "_fs-5 _light-gray" %>
        </div>
      </div>
    </div>
  </div>

  <div class="download-container _hcenter-positioner" id="download">
    <div class="content-box">
      <div class="_vcenter-positioner _hcenter-positioner _no-p-margin">
        <p class="_fs-3 _black">지금 소세지를 시작해보세요!</p>
      </div>
      <div class="download-text _text-center _no-p-margin">
        <%= simple_format @download, class: "_fs-4 _dark-gray _f-line-narrow" %>
      </div>

      <div class="download-icon-box _hcenter-positioner">
        <%= link_to @appstore do %>
            <%= image_tag "icon_google_play", class: "_store-icon" %>
        <% end %>
      </div>
    </div>
  </div>

  <footer class="_footer _vcenter-positioner">
    <%= image_tag "background_sausage2.jpg", class: "background-img" %>
    <p class="_fs-5 _white">@소세지 in 박근핵 해커톤 | 원지운, 조영제, 류혜진, 박근우, ChaeF</p>
  </footer>
</div>

sausage-landing/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>소세지, 소비자가 세상을 지킨다!</title>
    <%= csrf_meta_tags %>

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>